### ISSUE TITLE
Efforts in installing R package of ComplexHeatmap

### ISSUE THREAD

**Issue by yhan8** [broadinstitute/profiling-resistance-mechanisms#115]
Script 3.resistance/signature/7.profile-heatmaps.ipynb requires an R package of _ComplexHeatmap_ which requires the package of _Cairo_. https://anaconda.org/conda-forge/r-cairo. Cairo seems like an O.S. package (I am not sure though). I installed the Cairo package in brew but still cannot implement the package _ComplexHeatmap_ successfully.

**Comment by gwaygenomics** [comment]
We will need to figure this out, since we'll likely want to generate heatmaps for the signature features at some point in the future: https://github.com/broadinstitute/profiling-resistance-mechanisms/blob/c6953675e0381dc8d4e1285908b63735c570fad3/3.resistance-signature/7.profile-heatmaps.ipynb

**Comment by yhan8** [comment]
Turns out the way to make this package work is to remove the **@a387b860186be1d09249128be1ff46d13101e45d**

The correct code to install this package is as below:
`if (!("ComplexHeatmap" %in% rownames(installed.packages()))) {
    install_github("jokergoo/ComplexHeatmap")
}
suppressPackageStartupMessages(library(ComplexHeatmap))`

**Comment by gwaygenomics** [comment]
Great! Glad it was that simple!
