### ISSUE TITLE
Running Jupyter Notebook on AWS

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#23]
I am getting the following errors when trying to run a jupyter notebook with an R kernel on AWS. An example of the errors I am receiving is:

```bash
Error: package ‘base64enc’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

A description of this problem is provided [here](https://community.rstudio.com/t/issues-with-packages-after-updating-to-r-3-5-0/7639/31).

 I will document the packages that I needed to install with the given conda environment here:

* digest
* base64enc
* Rcpp
* rlang>0.4
* glue
* pillar
* tibble
* purrr
* tidyselect
* dplyr
* tidyr
* plyr
* mnormt
* foreign
* stringi
* reshape2
* colorspace
* scales
* lazyeval
* haven
* jsonlite
* lubridate
* readr
* readxl
* xml2
* tidyverse
* ggplot2
* htmltools
* backports
* bit
* bit64
* RSQLite
* dbplyr
* utf8

Lots of broken packages. Jupyter works again after reinstalling.

**Comment by shntnu** [comment]
Oh boy - not fun!
