### ISSUE TITLE
Strange Well Assignments for Batch 3 Mutant Clones

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#24]
I noticed this when examining potential plate artifacts.

It appears that in the file `backend/2019_06_25_Batch3/WTClones/WTClones_normalized_variable_selected.csv` there are two different samples measured in the same well.

Sample `BZ009` and `BZ010` are measured each three times. The wells indicated for `BZ009` are ["B10", "C10", "D10"] while the wells indicated for `BZ010` are ["B11", "C10", "D10"]. Going on this data, it looks like the two samples were measured in the same well! We know that this is not the case however. See below:

## Plate for Cell Count

![Screen Shot 2019-08-15 at 11 37 00 AM](https://user-images.githubusercontent.com/7340421/63106531-08a81480-bf51-11e9-8ebc-d418a983c74b.png)

Note that this data was extracted directly from the `sqlite` files.

## Plate for Replicate Correlation

![Screen Shot 2019-08-15 at 11 42 34 AM](https://user-images.githubusercontent.com/7340421/63106867-caf7bb80-bf51-11e9-8e94-9f862a16c439.png)

My guess is that `BZ010` should be occupying well "C11" and "D11" in the figure above.

## Recommendation

I am not sure we need to do anything at the moment, since we have the profiles already aggregated by well and this issue does not seem to have resulted in lost data. It is important to document though - maybe this persists in other projects? cc @bethac07 and @shntnu in case we've seen this before

**Comment by bethac07** [comment]
Megan and Adi provided the metadata CSVs this time; you're probably right about where the wells are, but we should confirm, update the metadata, and redo the analysis from annotation onward for that plate.

**Comment by gwaygenomics** [comment]
this was addressed several weeks ago, closing now.
