### ISSUE TITLE
Additional Experiments Comparing Feature Differences

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#26]
* t-test with nonnormalized data
* t-test with nonvariable selected data
* Plot feature distributions of top differential features using non-normalized data

**Comment by shntnu** [comment]
You might want to consider supervised, multivariate ways as well e.g. based on [random forests](https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html)
