### ISSUE TITLE
Potential Inconsistency in Platemap for Batch 1 (20X)

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#55]
Hi @mekelley and @ayberman,

I am working through implementing a PSMB5 signature analysis (described briefly here https://github.com/broadinstitute/profiling-resistance-mechanisms/issues/49#issuecomment-597829046)

This requires using data from early batches (batch 1 20x and batch 2). These are the only batches to have profiles for clones A and E (the only confirmed PSMB5 mutations), correct?

I noticed that there is a bit of a wonky platemap:

![2019_02_15_Batch1_20XHCT116bortezomib_plate_effects_cell_count](https://user-images.githubusercontent.com/7340421/76634881-ee510c00-651c-11ea-82d0-a5035b55225b.png)

Copy and pasted below:

| plate_map_name            | well_position | CellLine | Dosage |
|---------------------------|---------------|----------|--------|
| PlateMap_HCT116bortezomib | B03           | WT       | 0      |
| PlateMap_HCT116bortezomib | B04           | WT       | 0      |
| PlateMap_HCT116bortezomib | B05           | WT       | 0      |
| PlateMap_HCT116bortezomib | B06           | CloneA   | 0      |
| PlateMap_HCT116bortezomib | B07           | CloneA   | 0      |
| PlateMap_HCT116bortezomib | B08           | CloneA   | 0      |
| PlateMap_HCT116bortezomib | B09           | CloneE   | 0      |
| PlateMap_HCT116bortezomib | B10           | CloneE   | 0      |
| PlateMap_HCT116bortezomib | B11           | CloneE   | 0      |
| PlateMap_HCT116bortezomib | C03           | WT       | 0.7    |
| PlateMap_HCT116bortezomib | C04           | WT       | 0.7    |
| PlateMap_HCT116bortezomib | C05           | WT       | 0.7    |
| PlateMap_HCT116bortezomib | C06           | CloneA   | 0.7    |
| PlateMap_HCT116bortezomib | C07           | CloneA   | 0.7    |
| *PlateMap_HCT116bortezomib | F08           | CloneA   | 0.7    |
| PlateMap_HCT116bortezomib | C09           | CloneE   | 0.7    |
| PlateMap_HCT116bortezomib | C10           | CloneE   | 0.7    |
| PlateMap_HCT116bortezomib | C11           | CloneE   | 0.7    |
| PlateMap_HCT116bortezomib | D03           | WT       | 7      |
| PlateMap_HCT116bortezomib | D04           | WT       | 7      |
| PlateMap_HCT116bortezomib | D05           | WT       | 7      |
| PlateMap_HCT116bortezomib | D06           | CloneA   | 7      |
| PlateMap_HCT116bortezomib | D07           | CloneA   | 7      |
| PlateMap_HCT116bortezomib | D08           | CloneA   | 7      |
| PlateMap_HCT116bortezomib | D09           | CloneE   | 7      |
| PlateMap_HCT116bortezomib | D10           | CloneE   | 7      |
| PlateMap_HCT116bortezomib | D11           | CloneE   | 7      |
| PlateMap_HCT116bortezomib | E03           | WT       | 70     |
| PlateMap_HCT116bortezomib | E04           | WT       | 70     |
| PlateMap_HCT116bortezomib | E05           | WT       | 70     |
| PlateMap_HCT116bortezomib | E06           | CloneA   | 70     |
| PlateMap_HCT116bortezomib | E07           | CloneA   | 70     |
| PlateMap_HCT116bortezomib | E08           | CloneA   | 70     |
| PlateMap_HCT116bortezomib | E09           | CloneE   | 70     |
| PlateMap_HCT116bortezomib | E10           | CloneE   | 70     |
| PlateMap_HCT116bortezomib | E11           | CloneE   | 70     |

This doesn't impact analysis much at all, just confirming that the `F` above should be a `C`. Also, on the chance that this is indeed a small mistake - this stuff happens literally all the time, so no worries! 😹 It is good to confirm and clear up once identified. ( I didn't catch it in my original processing!)

**Comment by ayberman** [comment]
Hey Greg,

Regarding your questions about the plate map for 2-15-19, the well is indeed 8F. I accidentally plated the cells incorrectly in well C, so I replated that condition in well F. 

As for the batches, I'm pretty sure those are the only batches, but hopefully Megan can confirm?

**Comment by gwaygenomics** [comment]
> I accidentally plated the cells incorrectly in well C, so I replated that condition in well F.

Got it - thanks for the quick confirmation
