### ISSUE TITLE
Site Level Audit - Results

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#61]
In #60 I add code and results for performing an analysis audit (determining profile reproducibility and plate effects). I generate site level profiles in #59 for a subset of batches (batch 1 20x, batch 2, batch 5, batch 6, and batch 7). I show results below:

## Batch 1 - 20X

<details>
  <summary>Click to expand</summary>

### Cell Counts

![2019_02_15_Batch1_20XHCT116bortezomib_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273335-d698da80-7e70-11ea-9117-f999ee993ed4.png)

### Replicate Reproducibility

![2019_02_15_Batch1_20X_HCT116bortezomib_site_correlation](https://user-images.githubusercontent.com/7340421/79273404-ef08f500-7e70-11ea-9971-4f00678aa1c3.png)

</details>

## Batch 2

<details>
  <summary>Click to expand</summary>

### Cell Counts

![2019_03_20_Batch2207106_exposure320_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273447-ff20d480-7e70-11ea-86e4-40488819137a.png)

### Replicate Reproducibility

![2019_03_20_Batch2_207106_exposure320_site_correlation](https://user-images.githubusercontent.com/7340421/79273478-08aa3c80-7e71-11ea-86d5-b9156fe2dc69.png)

</details>

## Batch 5

<details>
  <summary>Click to expand</summary>

### Cell Counts

![2019_11_19_Batch5217755_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273521-211a5700-7e71-11ea-90e8-5746896224d1.png)

### Replicate Reproducibility

![2019_11_19_Batch5_217755_site_correlation](https://user-images.githubusercontent.com/7340421/79273557-2d9eaf80-7e71-11ea-8e06-b364103ded45.png)

</details>

## Batch 6

<details>
  <summary>Click to expand</summary>

### Cell Counts - Plate 217760

![2019_11_20_Batch6217760_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273596-3f805280-7e71-11ea-807b-83c11fe7c1ed.png)

### Replicate Reproducibility - Plate 217760

![2019_11_20_Batch6_217760_site_correlation](https://user-images.githubusercontent.com/7340421/79273642-5161f580-7e71-11ea-97c7-d7143c71a9ad.png)

### Cell Counts - Plate 217762

![2019_11_20_Batch6217762_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273619-46a76080-7e71-11ea-9808-af471e3bfafc.png)

### Replicate Reproducibility - Plate 217762

![2019_11_20_Batch6217762_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273688-63dc2f00-7e71-11ea-9168-9036514e4c28.png)

</details>

## Batch 7

<details>
  <summary>Click to expand</summary>

### Cell Counts - Plate 217766

![2019_11_22_Batch7217766_plate_effects_cell_count](https://user-images.githubusercontent.com/7340421/79273736-81a99400-7e71-11ea-9197-49056c33803f.png)

### Replicate Reproducibility - Plate 217766

![2019_11_22_Batch7_217766_site_correlation](https://user-images.githubusercontent.com/7340421/79273752-879f7500-7e71-11ea-8aa7-671ab5daa0a8.png)

### Cell Counts - Plate 217768

![2019_11_22_Batch7217768_plate_effects_cell_count_by_site](https://user-images.githubusercontent.com/7340421/79273782-8ff7b000-7e71-11ea-8342-dfe6daec52d6.png)

### Replicate Reproducibility - Plate 217768

![2019_11_22_Batch7_217768_site_correlation](https://user-images.githubusercontent.com/7340421/79273799-9554fa80-7e71-11ea-9e0d-5704467edf2b.png)

</details>

## Summary

There are many cells in nearly every site (some sites are completely missing) and the impact of plate effects appears minimal. I will proceed with analyzing these data downstream using site-level profiles.

**Comment by gwaygenomics** [comment]
I will also extend site level processing to other batches

**Comment by mekelley** [comment]
RE: site-layout (9 vs. 17, etc.)
It looks like while the campus is shutdown, I will not be able to access the site-maps for the wells (those experimental details are saved to the computer used for acquisition, which can’t be accessed remotely, and the facility is completely closed with no support staff). As soon as the facility is open, I will send an update regarding the organization of the sites in the wells.

**Comment by gwaygenomics** [comment]
> As soon as the facility is open, I will send an update regarding the organization of the sites in the wells.

Great, thanks for the update @mekelley - let's discuss these implications and their impact on timeline in our meeting tomorrow.

**Comment by gwaygenomics** [comment]
closing this issue given the decision in #70
