### ISSUE TITLE
Extracting XY location of sites

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/profiling-resistance-mechanisms#71]
get names all channel 1 images of well B03 (and then download)

```
parallel aws s3 ls s3://imaging-platform/projects/2018_05_30_ResistanceMechanisms_Kapoor/2019_11_19_Batch5/images/217755/20191119-TH-WTMUT-4h-0-7nMbz_B03_s{1}_w1 ::: 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 17
```

use `bftools` to get metadata

```
parallel ~/Downloads/bftools/showinf -nopix 20191119-TH-WTMUT-4h-0-7nMbz_B03_s{1}_w1* '>' site_{1}.txt ::: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 17
```

Extract stage information

```
parallel grep stage site_{1}.txt '>' stage_{1}.txt ::: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 17
```

Then format it using some SublimeText magic to make it a csv

```
site,x,y
2,29736.2,48083.54
3,31175.9,48083.64
1,28298.52,48083.46
4,29016.74,48802.78
5,29735.66,48802.68
7,28297.44,49522.04
6,30456.76,48802.82
14,30456.84,50241.42
15,28297.12,50960.68
17,31174.62,50960.62
12,29016.64,50241.36
13,29738.18,50241.36
11,31174.24,49522.04
10,30456.86,49522.08
8,29017.98,49522.16
9,29737.52,49522.08
```

```r
sites <- tribble(~site,~x,~y,
                 2,29736.2,48083.54,
                 3,31175.9,48083.64,
                 1,28298.52,48083.46,
                 4,29016.74,48802.78,
                 5,29735.66,48802.68,
                 7,28297.44,49522.04,
                 6,30456.76,48802.82,
                 14,30456.84,50241.42,
                 15,28297.12,50960.68,
                 17,31174.62,50960.62,
                 12,29016.64,50241.36,
                 13,29738.18,50241.36,
                 11,31174.24,49522.04,
                 10,30456.86,49522.08,
                 8,29017.98,49522.16,
                 9,29737.52,49522.08)

ggplot(sites, aes(x, y, label = site)) + geom_text()
```

![image](https://user-images.githubusercontent.com/1210428/80763298-38617180-8b0c-11ea-853e-9713e7800e06.png)

**Comment by gwaygenomics** [comment]
this impacts the decision outlined in #70 - I will quickly test to see if retaining sites:

```python
use_sites = [
  12, 13, 14, 8, 9, 10, 4, 5, 6
]
```

removes the massive site-to-site variability we see in these batches.

**Comment by gwaygenomics** [comment]
cc @mekelley - I am going to check consistency of this pattern as @shntnu suggested in our slack channel:

> Greg should do spot checks and verify that this pattern (include 16, which I think will be above site 13) is consistent across a random sampling of wells and then drop those

An additional check is to confirm with you if these settings were changed in any way **in batches 5, 6, and 7**. Less pressing is to know exactly which batches had this pattern of site collection.

Thanks!

**Comment by gwaygenomics** [comment]
two random wells in batches 6 and 7 indicate that this pattern is preserved

![image](https://user-images.githubusercontent.com/7340421/80816757-1f090580-8b9e-11ea-97ed-fb05cee85f71.png)

**Comment by mekelley** [comment]
This pattern looks correct but I can't verify anything until the High Throughput facility reopens and I can access the experiment files on the acquisition computer

**Comment by gwaygenomics** [comment]
I quickly tried filtering on `use_sites` (defined above) and we still see substantial site effects. A couple of reasons why we are still seeing this:

- The site layouts are not actually consistent
- We are not appropriately adjusting for batch effect in the four clone dataset

I will proceed with the decision as planned in #70.

Closing this issue for now. @mekelley feel free to open once we have an answer to site layouts.
