### ISSUE TITLE
Combining plates in Batch 9 and 10

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#91]
The data are described in more detail in #89. This issue is to discuss the results and interpretations of #90 

## Update 11/16/20

We discussed this plate layout in detail, and determined that the data are still usable. Our primary question is whether or not we can distinguish resistant clones from sensitive clones. We do not need drug treatment and we only need the DMSO-only plates to determine this.

## Critical Issue

> Specifically, each plate contains only a single treatment (either DMSO or drug). This prevents us from performing our traditional per-plate normalization strategy, and might make it impossible for us to reliably combine data across plates.

## Approach to Address

1. Determine the extent of the problem
    * Combine all plates together within batch
    * Apply PCA retaining 20 components, and then apply an ANOVA using Treatment, Clone, and Plate (and an interaction term between treatment and plate) as factors
    * Visualize the ANOVA F scores per factor
2. Attempt to solve the problem in a naive way
    * Concatenate "augmented" (aggregated, unnormalized) per-plate "matches" (meaning all the plates that have DMSO and compound treatments for the specific clones)
    * Apply whole-plate standardization
    * Apply the steps outlined in the first step above

## Results

![normalized_pca_anova_batch_effects](https://user-images.githubusercontent.com/7340421/99283133-93d22300-2802-11eb-8621-1398ae6f6c8e.png)

* Batch 7 and Batch 8 have good plate designs, Batch 9 and Batch 10 have suboptimal designs.
* All four batches don't have plate effects! 🎉 
* However, Batch 9 and Batch 10 only have very little impact for the Metadata treatement factor ☹️ - this is because normalization occurs per plate, and each plate only has one treatment (either DMSO or drug)

![naive_correction_pca_anova_batch_effects](https://user-images.githubusercontent.com/7340421/99283158-9cc2f480-2802-11eb-87f1-7a2d22a39c10.png)

* A naive attempt (described above) explodes the impact of batch.
* Maybe this is ok? Perhaps we can regress out those components and move on?

cc'ing @shntnu @AnneCarpenter  - Comments/suggestions welcome, if there are any. Can we salvage these data? (there are 14 plates...)

**Comment by shntnu** [comment]
In a separate thread, @AnneCarpenter said the following; does that address the main concern you have in this issue @gwaygenomics ?

> The thing Greg was worried about (no plates had DMSO + drug treated on the same plate) is less worrisome since our primary goal is to find resistant-clone-specific signatures in untreated cells. How the signature changes upon drug treatment is a side note (ie something reviewers will probably ask about out of curiosity but it doesn't validate or disprove anything, just interesting to know).

**Comment by gwaygenomics** [comment]
yep - not all is lost.

BUT, having plate layout change from all plates containing treatment to plates without treatment 1) limits our ability to combine data across plates, and 2) may have unforseen consequences to feature measurements after normalization.
