### ISSUE TITLE
Bortezomib signature platemap effect?

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#98]
Confirm that platemap is not influencing the signature we observed in #94

**Comment by AnneCarpenter** [comment]
A simple visualization of the different samples across plates/batches would do!

**Comment by gwaygenomics** [comment]
Based on quick visualizations, there do not appear to be any strong plate position effects for all plates:

Here is the holdout plate:

## Signature scores

![2021_03_03_Batch14_219901_signature_plate_effect](https://user-images.githubusercontent.com/7340421/116298160-1aa00a00-a76a-11eb-9154-e39392ca353a.png)

## Full plate layout

![2021_03_03_Batch14219901_plate_effects_replicates](https://user-images.githubusercontent.com/7340421/116298069-03611c80-a76a-11eb-88c8-a79d7d32dbb7.png)

**Comment by gwaygenomics** [comment]
Figures for all 7 plates are here: https://github.com/broadinstitute/profiling-resistance-mechanisms/tree/9feaa87880f332ef2532cd7aada893927a8c0888/3.resistance-signature/figures/plate_effects

**Comment by AnneCarpenter** [comment]
Super, I was looking mainly for bad plate *layout* rather than bad plate effects now that I think of it, and these visualizations effectively show there is nothing fishy going on for either (also that Batches 15 onwards look pretty great!) @gwaygenomics
